### ISSUE TITLE
Implementing Date Histogram aggregation?

### ISSUE THREAD

**Issue by skind** [Vycka/ElasticSearch.Client#1]
Your Libs works very well - thankx for sharing it. 
One thing I'm missing is the implementation of the Histogram functionality - 
can I hope for it?

**Comment by Vycka** [comment]
Hello, thanks for your feedback.
Do you mean Histogram aggregation or something else?
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html

And by the way, which version do you use?

**Comment by skind** [comment]
Hey,
thank you very much for the fast answer!
My Problem is: I have to create a overview of time/date series to generate charts. My chief is asking the question “How many things did we generate in a time/date period – and this per hour/day/week/month”.
As far as I understood the following link is that what I need:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html

..with this response I can generate the time series?

I’m not very experienced with elasticsearch, but with your Lib I can handle the communication and it work immediately –so I’m very exicted about the lib!! This is the reason I contacted you and I hope you
can help me/us.

Thankx in advance,
Simon

**Comment by Vycka** [comment]
Implemented Histogram and Date Histogram

https://github.com/Vycka/ElasitcSearchClient/blob/master/src/ElasticSearch.Playground/Samples/Aggregates/DateHistogram.cs
https://github.com/Vycka/ElasitcSearchClient/blob/master/src/ElasticSearch.Playground/Samples/Aggregates/Histogram.cs

Will this do the job for you, or you need something more?

Nuget 0.1.2.
Keep in mind, that if you are still using 0.0.x version, there might be some namespace breaking changes.

**Comment by skind** [comment]
..great, great,great!!!  It seems that is THE thing I was looking for – will download all the stuff and try it ..
Great Response – you got my 5 
Thank you very much,
Simon

**Comment by skind** [comment]
..yeahhhhh – it worked!! I created my filter and it worked immediately!! Great Library to work with – please continue!!
